version: '3.4'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  mattcanello.newsfeed.rssreader:
    image: ${DOCKER_REGISTRY-}mattcanellonewsfeedrssreader
    build:
      context: .
      dockerfile: ../MattCanello.NewsFeed.RssReader/Dockerfile

  mattcanello.newsfeed.rssreader-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "rss-reader", "-app-port", "80", "--components-path", "./components" ]
    depends_on:
      - mattcanello.newsfeed.rssreader
      - redis
    network_mode: "service:mattcanello.newsfeed.rssreader"
    volumes:
      - "../dapr/components/:/components"

volumes:
  redis_data:
    driver: local