version: '3.4'

services:
  mattcanello.newsfeed.rssreader:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mattcanello.newsfeed.cronapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

