version: '3.4'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure
    ports:
      - 22181:2181
    volumes:
      - 'zk_data:/var/lib/zookeeper/data'
      - 'zk_txn_logs:/var/lib/zookeeper/log'
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 9101:9101
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - 'kafka_data:/var/lib/kafka/data'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=news-feed
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    networks:
      - elastic
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    restart: 'unless-stopped'
    networks:
      - elastic

  mattcanello.newsfeed.rssreader:
    image: ${DOCKER_REGISTRY-}mattcanellonewsfeedrssreader
    build:
      context: ..
      dockerfile: ./MattCanello.NewsFeed.RssReader/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mattcanello.newsfeed.rssreader-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "rss-reader", "-app-port", "80", "--components-path", "./components" ]
    depends_on:
      - mattcanello.newsfeed.rssreader
      - redis
      - kafka
    restart: on-failure
    network_mode: "service:mattcanello.newsfeed.rssreader"
    volumes:
      - "../dapr/components/:/components"

  mattcanello.newsfeed.cronapi:
    image: ${DOCKER_REGISTRY-}mattcanellonewsfeedcronapi
    build:
      context: ..
      dockerfile: ./MattCanello.NewsFeed.CronApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      
  mattcanello.newsfeed.cronapi-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "cron-api", "-app-port", "80", "--components-path", "./components" ]
    depends_on:
      - mattcanello.newsfeed.cronapi
      - redis
      - kafka
    restart: on-failure
    network_mode: "service:mattcanello.newsfeed.cronapi"
    volumes:
      - "../dapr/components/:/components"

volumes:
  redis_data:
    driver: local

  zk_data:
    driver: local

  zk_txn_logs:
    driver: local

  kafka_data:
    driver: local

  elasticsearch-data:
    driver: local

  kibana-data:
    driver: local

networks:
  elastic:
    driver: bridge  