apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: process
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "rss-publish-commands"
  - name: clientID
    value: "rss-reader"
  - name: consumerGroup
    value: "rss-reader"
scopes:
  - rss-reader
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: index
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "rss-entries"
  - name: clientID
    value: "search-api"
  - name: consumerGroup
    value: "search-api"
scopes:
  - search-api
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: update-feed
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "rss-channels"
  - name: clientID
    value: "admin-api"
  - name: consumerGroup
    value: "admin-api"
scopes:
  - admin-api
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: create-feed
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "created-feeds"
  - name: clientID
    value: "rss-reader"
  - name: consumerGroup
    value: "rss-reader"
scopes:
  - rss-reader
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: register-feed
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "created-feeds"
  - name: clientID
    value: "cron-api"
  - name: consumerGroup
    value: "cron-api"
scopes:
  - cron-api
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: new-entry
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
  - name: direction
    value: "input"
  - name: topics
    value: "indexed-documents"
  - name: clientID
    value: "frontend-server"
  - name: consumerGroup
    value: "frontend-server"
scopes:
  - frontend-server