apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rssentriestopic
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: direction
    value: "output"
  - name: publishTopic
    value: "rss-entries"
  - name: clientID
    value: "rss-reader"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rsschannelstopic
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092,localhost:9092"
  - name: authType
    value: "none"
  - name: direction
    value: "output"
  - name: publishTopic
    value: "rss-channels"
  - name: clientID
    value: "rss-reader"