apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rssreaderstate
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - rss-reader
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cronstatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - cron-api