//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattCanello.NewsFeed.RssReader.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattCanello.NewsFeed.RssReader.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rss version=&quot;0.91&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;copyright&gt;Copyright 1997-1999 UserLand Software, Inc.&lt;/copyright&gt;
        ///		&lt;pubDate&gt;Thu, 08 Jul 1999 07:00:00 GMT&lt;/pubDate&gt;
        ///		&lt;lastBuildDate&gt;Thu, 08 Jul 1999 16:20:26 GMT&lt;/lastBuildDate&gt;
        ///		&lt;docs&gt;http://my.userland.com/stories/storyReader$11&lt;/docs&gt;
        ///		&lt;description&gt;News and commentary from the cross-platform scripting community.&lt;/description&gt;
        ///		&lt;link&gt;http://www.scripting.com/&lt;/link&gt;
        ///		&lt;title&gt;Scripting News&lt;/title&gt;
        ///		&lt;image&gt;
        ///			&lt;link&gt;http://www.script [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_091 {
            get {
                return ResourceManager.GetString("sample-rss-091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;//feeds.folha.uol.com.br/rss/style.xsl&quot; ?&gt;
        ///
        ///&lt;rss version=&quot;0.91&quot;&gt;
        ///	&lt;channel&gt;
        ///
        ///		&lt;title&gt;Folha de S.Paulo - Tec - Principal&lt;/title&gt;
        ///		&lt;link&gt;https://redir.folha.com.br/redir/online/tec/rss091/*https://www1.folha.uol.com.br/tec/&lt;/link&gt;
        ///		&lt;description&gt;Primeiro jornal em tempo real em língua portuguesa&lt;/description&gt;
        ///		&lt;language&gt;pt-br&lt;/language&gt;
        ///		&lt;copyright&gt;Copyright Folha de S.Paulo. Todos os direitos reservados.&lt;/copyri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_folha_spaulo_tec1 {
            get {
                return ResourceManager.GetString("sample-rss-folha-spaulo-tec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;//feeds.folha.uol.com.br/rss/style.xsl&quot; ?&gt;
        ///
        ///&lt;rss version=&quot;0.91&quot;&gt;
        ///	&lt;channel&gt;
        ///
        ///		&lt;title&gt;Folha de S.Paulo - Tec - Principal&lt;/title&gt;
        ///		&lt;link&gt;https://redir.folha.com.br/redir/online/tec/rss091/*https://www1.folha.uol.com.br/tec/&lt;/link&gt;
        ///		&lt;description&gt;Primeiro jornal em tempo real em língua portuguesa&lt;/description&gt;
        ///		&lt;language&gt;pt-br&lt;/language&gt;
        ///		&lt;copyright&gt;Copyright Folha de S.Paulo. Todos os direitos reservados.&lt;/copyri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_folha_spaulo_tec2 {
            get {
                return ResourceManager.GetString("sample-rss-folha-spaulo-tec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;title&gt;The Guardian&lt;/title&gt;
        ///		&lt;link&gt;https://www.theguardian.com/uk&lt;/link&gt;
        ///		&lt;description&gt;Latest news, sport, business, comment, analysis and reviews from the Guardian, the world&apos;s leading liberal voice&lt;/description&gt;
        ///		&lt;language&gt;en-gb&lt;/language&gt;
        ///		&lt;copyright&gt;Guardian News and Media Limited or its affiliated companies. All rights reserved. 2024&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_the_guardian_uk {
            get {
                return ResourceManager.GetString("sample-rss-the-guardian-uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xml:lang=&quot;en&quot;&gt;
        ///	&lt;title&gt;The Verge -  All Posts&lt;/title&gt;
        ///	&lt;icon&gt;https://cdn.vox-cdn.com/community_logos/52801/VER_Logomark_32x32..png&lt;/icon&gt;
        ///	&lt;updated&gt;2024-04-25T10:39:57-04:00&lt;/updated&gt;
        ///	&lt;id&gt;https://www.theverge.com/rss/full.xml&lt;/id&gt;
        ///	&lt;link type=&quot;text/html&quot; href=&quot;https://www.theverge.com/&quot; rel=&quot;alternate&quot;/&gt;
        ///	&lt;entry&gt;
        ///		&lt;published&gt;2024-04-25T10:39:57-04:00&lt;/published&gt;
        ///		&lt;updated&gt;2024-04-25T10:39:57-04:00&lt;/updated&gt;
        ///		&lt;titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_the_verge {
            get {
                return ResourceManager.GetString("sample-rss-the-verge", resourceCulture);
            }
        }
    }
}
