//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattCanello.NewsFeed.RssReader.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattCanello.NewsFeed.RssReader.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE rss SYSTEM &quot;http://my.netscape.com/publish/formats/rss-0.91.dtd&quot;&gt;
        ///&lt;rss version=&quot;0.91&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;copyright&gt;Copyright 1997-1999 UserLand Software, Inc.&lt;/copyright&gt;
        ///		&lt;pubDate&gt;Thu, 08 Jul 1999 07:00:00 GMT&lt;/pubDate&gt;
        ///		&lt;lastBuildDate&gt;Thu, 08 Jul 1999 16:20:26 GMT&lt;/lastBuildDate&gt;
        ///		&lt;docs&gt;http://my.userland.com/stories/storyReader$11&lt;/docs&gt;
        ///		&lt;description&gt;News and commentary from the cross-platform scripting community.&lt;/description&gt;
        ///		&lt;link&gt;http://www.scripting.com/&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_091 {
            get {
                return ResourceManager.GetString("sample-rss-091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;title&gt;The Guardian&lt;/title&gt;
        ///		&lt;link&gt;https://www.theguardian.com/uk&lt;/link&gt;
        ///		&lt;description&gt;Latest news, sport, business, comment, analysis and reviews from the Guardian, the world&apos;s leading liberal voice&lt;/description&gt;
        ///		&lt;language&gt;en-gb&lt;/language&gt;
        ///		&lt;copyright&gt;Guardian News and Media Limited or its affiliated companies. All rights reserved. 2024&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_rss_the_guardian_uk {
            get {
                return ResourceManager.GetString("sample-rss-the-guardian-uk", resourceCulture);
            }
        }
    }
}
