name: 'Admin API Container App'
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: adminapi
  CONTAINER_APP_ENVIRONMENT_NAME: tcc-pucrs-pos-graduacao-full-stack
  RESOURCE_GROUP: tcc-pucrs-pos-graduacao-full-stack
  CONTAINER_REGISTRY_NAME: tccpucrsposgraduacaofullstack
  CONTAINER_REGISTRY_LOGIN_SERVER: tccpucrsposgraduacaofullstack.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.tcc_pucrs_pos_graduacao_full_stack_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.tccpucrsposgraduacaofullstack_USERNAME_C61C }}
        acrPassword: ${{ secrets.tccpucrsposgraduacaofullstack_PASSWORD_C61C }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        dockerfilePath: code/MattCanello.NewsFeed.AdminApi/Dockerfile
