name: 'Frontend Client Container App'
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  NODE_VERSION: 18
  CONTAINER_APP_NAME: frontendclient
  CONTAINER_APP_ENVIRONMENT_NAME: tcc-pucrs-pos-graduacao-full-stack
  RESOURCE_GROUP: tcc-pucrs-pos-graduacao-full-stack
  CONTAINER_REGISTRY_NAME: tccpucrsposgraduacaofullstack
  CONTAINER_REGISTRY_LOGIN_SERVER: tccpucrsposgraduacaofullstack.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
       node-version:  ${{ env.NODE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.tcc_pucrs_pos_graduacao_full_stack_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.tccpucrsposgraduacaofullstack_USERNAME_82CB }}
        acrPassword: ${{ secrets.tccpucrsposgraduacaofullstack_PASSWORD_82CB }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        dockerfilePath: code/MattCanello.NewsFeed.Frontend/mattcanello.newsfeed.frontend.client/Dockerfile.prod
