name: 'Execução de Testes em PRs'
on:
  pull_request:
    types: [ opened, edited, reopened, ready_for_review ]

jobs:
  RssReader:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Restore
      run: dotnet restore ./code/MattCanello.NewsFeed.RssReader.Tests/MattCanello.NewsFeed.RssReader.Tests.csproj
    - name: Build
      run: dotnet build ./code/MattCanello.NewsFeed.RssReader.Tests/MattCanello.NewsFeed.RssReader.Tests.csproj --no-restore
    - name: Test
      run: dotnet test ./code/MattCanello.NewsFeed.RssReader.Tests/MattCanello.NewsFeed.RssReader.Tests.csproj
  CronApi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Restore
      run: dotnet restore ./code/MattCanello.NewsFeed.CronApi.Tests/MattCanello.NewsFeed.CronApi.Tests.csproj
    - name: Build
      run: dotnet build ./code/MattCanello.NewsFeed.CronApi.Tests/MattCanello.NewsFeed.CronApi.Tests.csproj --no-restore
    - name: Test
      run: dotnet test ./code/MattCanello.NewsFeed.CronApi.Tests/MattCanello.NewsFeed.CronApi.Tests.csproj
