name: 'Execução de Testes em PRs'
on:
  pull_request:
    types: [ opened, edited, reopened, ready_for_review ]

jobs:
  Solution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Restore
      run: dotnet restore ./code/MattCanello.NewsFeed.sln
    - name: Build
      run: dotnet build ./code/MattCanello.NewsFeed.sln --no-restore
    - name: Test
      run: dotnet test ./code/MattCanello.NewsFeed.sln